<?php

$trad = [
    "duck" => "pixel art d'un canard",
    "sky_img" => "pixel art d'un ciel étoilé",
    "title" => "Vous vous trouvez sur le portfolio de Florent Hardy.<br/>Cliquez sur les flèches pour naviguer.<br/>En espérant que vous profiterez de votre séjour !",
    "about" => "A propos",
    "game1" => "Démineur",
    "game2" => "C:/ > fhpaint.exe",
    "game3" => "Morpion",
    "game4" => "En travaux",
    "inwork" => "Je veux plus, toujours plus de contenu !",
    "anim1" => "Double pendule",
    "anim2" => "Quicksort",
    "anim3" => "Simulation orbite",
    "err_canvas" => "Votre navigateur ne supporte pas cet affichage.",
    "button1" => "Nouvelle grille",
    "access" => "Accessibilité",
    "mine_b1" => "Découvrir case",
    "mine_b2" => "Poser drapeau",
    "savoir_plus" => "En savoir plus",
    "demarrer" => "Démarrer",
    "reset" => "Réinitialiser",
    "dem/arr" => "Démarrer / Arrêter",
    "nv_pendule" => "Nouveau pendule",
    "stop" => "Arrêter",
    "color" => "Couleur : ",
    "empty_canv" => "Vider canvas",
    "contact" => "L'auteur du portfolio est disponible : </br>par mail : <type='email'>definitelyNot@fakeAdress.com </br>par téléphone : 07 96 02 40",
    "connect" => "Connectez vous !",
    "mdp" => "Mot de passe :",
    "mdp_aff" => "Afficher le mot de passe",
    "connect_button" => "Se connecter",
    "nav_home" => "Page principale",
    "nav_jeu" => "Jeux",
    "other_lang" => "English",
    "morependulum" => "Les pendules : un acheté, un offert !",
    "moresort" => "svp soyez doux sur les boutons ils viennent d'être embauchés",
    "moreorbit" => "Projet réalisé pour l'UE Programmation Web 1 avec l'étudiant Kevin Hentz",
    "moresweep" => "Jeu développé pendant le mois de la fierté LGBT, expliquant les couleurs du drapeau sensé représenter l'absence de danger. </br> Merci de ne pas regarder le code, vous ne pourrez pas dire que je ne vous ai pas prévenu !",
    "morepaint" => "Outil utilisé pour dessinner le canard vedette du site. Si vous ne saviez pas vous pouvez chouchouter le canard !",
    "moretic" => "L'algorithme minmax a été utilisé pour développer l'IA. L'étalage alpha beta et les neural network viendront plus tard",
    "nav_id" => "Mon compte"
];