<?php

$trad = [
    "duck" => "duck pixel art",
    "sky_img" => "starry sky pixel art",
    "title" => "You are reading Florent Hardy's portfolio.<br/>Use the arrows to navigate.<br/> Enjoy your stay !",
    "about" => "About",
    "game1" => "Minesweeper",
    "game2" => "C:/ > fhpaint.exe",
    "game3" => "Tic Tac Toe",
    "anim1" => "Double pendulum",
    "anim2" => "Quicksort",
    "anim3" => "Orbit simulation",
    "err_canvas" => "Your browser does not support canvas drawings.",
    "button1" => "New grid",
    "access" => "Accessibility",
    "mine_b1" => "Uncover",
    "mine_b2" => "Place flag",
    "savoir_plus" => "Learn more",
    "demarrer" => "Start",
    "reset" => "Reset",
    "dem/arr" => "Start / Stop",
    "nv_pendule" => "New pendulum",
    "stop" => "Stop",
    "color" => "Color : ",
    "empty_canv" => "Empty canvas",
    "contact" => "The author is available : </br>via mail : definitelyNot@fakeAdress.com </br>via phone : 07 96 02 40",
    "connect" => "Sign in !",
    "mdp" => "Password :",
    "mdp_aff" => "Show password",
    "connect_button" => "Sign in",
    "nav_home" => "Home",
    "nav_jeu" => "Games",
    "other_lang" => "Français"
];