<?php

$trad = [
    "duck" => "pixel art d'un canard",
    "sky_img" => "pixel art d'un ciel étoilé",
    "title" => "Vous vous trouvez sur le portfolio de Florent Hardy.<br/>Cliquez sur les flèches pour naviguer.<br/>En espérant que vous profiterez de votre séjour !",
    "about" => "A propos",
    "game1" => "Démineur",
    "game2" => "C:/ > fhpaint.exe",
    "game3" => "Morpion",
    "anim1" => "Double pendule",
    "anim2" => "Quicksort",
    "anim3" => "Simulation orbite",
    "err_canvas" => "Votre navigateur ne supporte pas cet affichage.",
    "button1" => "Nouvelle grille",
    "access" => "Accessibilité",
    "mine_b1" => "Découvrir case",
    "mine_b2" => "Poser drapeau",
    "savoir_plus" => "En savoir plus",
    "demarrer" => "Démarrer",
    "reset" => "Réinitialiser",
    "dem/arr" => "Démarrer / Arrêter",
    "nv_pendule" => "Nouveau pendule",
    "stop" => "Arrêter",
    "color" => "Couleur : ",
    "empty_canv" => "Vider canvas",
    "contact" => "L'auteur du portfolio est disponible : </br>par mail : definitelyNot@fakeAdress.com </br>par téléphone : 07 96 02 40",
    "connect" => "Connectez vous !",
    "mdp" => "Mot de passe :",
    "mdp_aff" => "Afficher le mot de passe",
    "connect_button" => "Se connecter",
    "nav_home" => "Page principale",
    "nav_jeu" => "Jeux",
    "other_lang" => "English"
];